### ISSUE TITLE
Option to provide file:// URL to results from FSRiver

### ISSUE THREAD

**Issue by IanMayo** [scrutmydocs/scrutmydocs#55]
I'm indexing my local machine.

Imagine that when I do a search, ScrutMyDocs finds a matching MS Word document.  When I click on the link, my browser downloads a copy of the MS Word document to my downloads folder.

What I really wanted was to open the original MS Word document, so I can carry on editing it.

I believe this requirement would be met by providing a "Link direct to File URL" in the FSRiver options page.

**Comment by dadoonet** [comment]
This repo is not maintained and won't have any feature implemented.
Instead, look at [the Workplace Search project](https://www.elastic.co/enterprise-search/workplace-search) which is much more mature and production ready. It's available under the free basic license.
