### ISSUE TITLE
Download link is not working

### ISSUE THREAD

**Issue by sjelfull** [scrutmydocs/scrutmydocs#72]
https://github.com/downloads/scrutmydocs/scrutmydocs/scrutmydocs-0.3.0.war gives 404

**Comment by dadoonet** [comment]
This repo is not maintained and won't have any feature implemented.
Instead, look at [the Workplace Search project](https://www.elastic.co/enterprise-search/workplace-search) which is much more mature and production ready. It's available under the free basic license.
