### ISSUE TITLE
How we create a separate node for diff diff users?

### ISSUE THREAD

**Issue by ankur99999** [scrutmydocs/scrutmydocs#83]
Hi,

I like your project, And it's awesome, But i am unable to understand it's flow and how its working.
So i am using reverse engineering to understand this project. it's very helpful for us if you provide a document with this.

We are trying to add new feature in it. Suppose i run this on my server and authenticating users by login details. So my question is how i can create diff diff node for diff diff users, SO they can upload and and search with in their area.

**Comment by dadoonet** [comment]
Thank you for your interest. 
We started to rewrite it from scratch as some feature will change in Elasticsearch.
It was not designed to be multi tenant. But this is definitely something we should think about.

**Comment by ankur99999** [comment]
OK, Thanks for quick response. So if i am able to create diff diff node, then this will work( A user can bound in their own area)?

**Comment by dadoonet** [comment]
May be I don't understand what is a diff diff node but scrutmydocs supports connection on only one cluster.

**Comment by ankur99999** [comment]
I am thinking about limit  a user with in their area,  Suppose i user upload 10 documents and user B upload 20 different  documents. So i am thinking how we can implement this  feature that user A can't search in user B documents. Means user A can search with in his 10 documents and user B can search with in 20 documents. For this,, I supposing we can do this by creating different different nodes.

**Comment by dadoonet** [comment]
Different indices or aliases. Yes.
That's what I have in mind.

Basically add the user name in your document metadata, then a filtered alias. And query the right alias.

**Comment by ankur99999** [comment]
Ok, Thanks. I am trying to do that. 
I am using this code for adding client1

         IndexResponse response = client
					.prepareIndex("client1", document.getType(),
							document.getId())
					.setSource(extractDocument(document)).execute()
					.actionGet();

And this code for getting data:-

           GetResponse responseEs = client.prepareGet("client1", type, id)
                .setFields(
                        FsRiverUtil.Doc.ATTACHMENT,
                        FsRiverUtil.Doc.META + "." + FsRiverUtil.Doc.Meta.TITLE,
                        FsRiverUtil.Doc.FILE + "." + FsRiverUtil.Doc.File.CONTENT_TYPE)

        .get();


I am referring this http://java.dzone.com/articles/elasticsearch-java-api  
But i am not able to see my docs and not able to search anything.

**Comment by dadoonet** [comment]
I don't see anything wrong with your code.
May be the mapping is missing and was not applied for this new index `client1`?

**Comment by ankur99999** [comment]
Got it, I am not using 'client1' indexing in searchService.
     
        	org.elasticsearch.action.search.SearchResponse searchHits = esClient
				.prepareSearch()
                .setIndices("client1")

Can i pass dynamic names at run-time, so diff diff users can control their area? 
According to me we can pass, Am i right?

**Comment by dadoonet** [comment]
If I understand correctly what you wrote, yes you can.

**Comment by ankur99999** [comment]
I am trying to say that users can register and login in an application, And i will pass their client-id (Talking about client1) to separate their areas.
 Can i do this?

**Comment by dadoonet** [comment]
Sure.

**Comment by dadoonet** [comment]
This repo is not maintained and won't have any feature implemented.
Instead, look at [the Workplace Search project](https://www.elastic.co/enterprise-search/workplace-search) which is much more mature and production ready. It's available under the free basic license.
