### ISSUE TITLE
Indexing Quota

### ISSUE THREAD

**Issue by ghost** [scrutmydocs/scrutmydocs#84]
Hi , 

With 0.3.0-SNAPSHOT I was only able to push 100 pages of document (911 documents)  to application.
My river folder contains around 50 gb of data.

Is there a limitation or configuration that I can change? 

0.2.0 version was okey to push 50gb of data, around 3 million files.

Or it shows results in maximum 100 pages ? 

Thanks.

**Comment by dadoonet** [comment]
This repo is not maintained and won't have any feature implemented.
Instead, look at [the Workplace Search project](https://www.elastic.co/enterprise-search/workplace-search) which is much more mature and production ready. It's available under the free basic license.
